version: '3'
services:
  api:
    image: 'node:latest'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: >
      bash -c "npm run migrate --prefix ./app && npm start --prefix ./app"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password

